// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://garhwlhcsleuwjhqjrnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhcmh3bGhjc2xldXdqaHFqcm52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mzg4MzMsImV4cCI6MjA3NDAxNDgzM30.xYx1470Z6i0O_w20ndzM63TgrIG-nNXuWk4joJVVSOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});